version: '3'

services:
  wmb:
    image: ghcr.io/cfindlayisme/wmb:latest
    environment: 
        - IRC_SERVER=
        - IRC_NICK=
        - IRC_CHANNEL=
        - PASSWORD=
    ports:
        - "8080:8080"
    restart: always